on:
  rss:
    url:
      - http://weekly.pychina.org/feeds/all.atom.xml
      - http://applefans.today/feed
    config:
      - debug: true
      - cron: "0 8 * * *"
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Add a new card to Asana
        uses: actionsflow/axios@v1
        with:
          url: https://app.asana.com/api/1.0/tasks
          method: 'POST'
          headers: '{ "Content-Type": "application/json", "Authorization": "${{ secrets.ASANA_TOKEN }}" }'
          data: |
            {
              "name": "actionflow | ${{ on.rss.outputs.title }}",
              "html_notes": "<body>${{ on.rss.outputs.content }}\n\n<a href='${{ on.rss.outputs.link }}'>Trello Link</a></body>",
              "projects": ["${{ secrets.asana_project }}"],
              "workspace": "${{ secrets.asana_workspace }}"
            }
