on:
  poll:
    url: https://app.asana.com/api/1.0/tags/1198197485416173/tasks?completed_since=now
    itemsPath: data
    shouldIncludeRawBody: true
    requestConfig:
      method: GET
      headers:
        Authorization: ${{ secrets.ASANA_TOKEN }}

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          # title: ${{ on.poll.outputs.data.name }}
          rawBody: ${{ toJSON(on.poll.outputs.raw__body) }}
        run: |
          echo "ok"
