on:
  poll:
    url: https://app.asana.com/api/1.0/tags/1198197485416173/tasks?completed_since=now&opt_fields=name,due_at
    itemsPath: data
    deduplicationKey: gid
    # shouldIncludeRawBody: true
    requestConfig:
      method: GET
      headers:
        Authorization: ${{ secrets.ASANA_TOKEN }}

# jobs:
#   print:
#     name: Print
#     runs-on: ubuntu-latest
#     steps:
#       - name: Print Outputs
#         env:
#           title: ${{ on.poll.outputs.name }}
#           task_id: ${{ on.poll.outputs.gid }}
#           # rawBody: ${{ toJSON(on.poll.outputs.raw__body) }}
#         run: |
#           echo "$title"
#           echo "task id: $task_id"

jobs:
    asana-task-detail:
        name: 'Get Task Detail'
        runs-on: ubuntu-latest
        steps:
            - name: 'Print Data'
              id: result
              # if: steps.api.outputs.data.due_at != null
              # env:
              #   title: ${{ toJSON(steps.api.outputs.data) }}
              run: |
                echo gid: ${{ on.poll.outputs.gid }}
                echo due: ${{ on.poll.outputs.due_at }}
