on:
  script:
    run: |
      const result = await helpers.axios.get("https://app.asana.com/api/1.0/tags/1198197485416173/tasks?completed_since=now&opt_fields=name,due_at,modified_at", {headers: {"Authorization": "<<<${{ secrets.ASANA_TOKEN }}>>>"}})
      return result.data
    deduplicationKey: gid
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.script.outputs.name}}
          gid: ${{on.script.outputs.gid}}
          mod: ${{on.script.outputs.modified_at}}
        run: |
          echo title: $title
          echo gid: $gid
          echo mod: $mod
