on:
  webhook:

jobs:
  airtable_f8CCf:
    name: get records from airtable
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.webhook.outputs.method }}
          body: ${{ toJson(on.webhook.outputs.body) }}
          headers: ${{ toJson(on.webhook.outputs.headers) }}
        run: |
          echo method: $method
          echo headers $headers
          echo body: $body
      - name: 'Get the record from airtable'
        uses: actionsflow/axios@v1
        with:
          url: https://api.airtable.com/v0/appzz4hbwcoJzQaF2/Project%20Database?api_key=${{secrets.AIRTABLE_API_TOKEN}}
          method: GET
          content-type: application/json
          params: |
           {
              "filterByFormula": "AND({Title}='${{on.webhook.outputs.body.Title}}',SEARCH('Clockify',{Target}),{Clockify_ID=''})",
              "maxRecords": 1
            }
