on:
  webhook:

jobs:
  airtable_f8CCf:
    name: get records from airtable
    runs-on: ubuntu-latest
    steps:
      - name: Get outputs
        uses: actions/github-script@v2
        id: get-query-encoding
        env:
          OUTPUTS_PATH: ${{ on.webhook.outputs.body.Title }}
        with:
          script: |
            const outputs = "https://api.airtable.com/v0/appzz4hbwcoJzQaF2/Project%20Database?" + "&filterByFormula=" + encodeURIComponent(`${process.env.OUTPUTS_PATH}`);
            return outputs

      - name: Get result
        run: |
          echo RES: "${{steps.get-query-encoding.outputs.result}}"
          echo OUTPUT: "${{steps.get-query-encoding.outputs}}"
