on:
  webhook:

jobs:
  airtable_f8CCf:
    name: add records to airtable
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.webhook.outputs.method }}
          body: ${{ toJson(on.webhook.outputs.body) }}
          headers: ${{ toJson(on.webhook.outputs.headers) }}
        run: |
          echo body: $body
      - name: 'Add a new record to Project Database'
        uses: actionsflow/axios@v1
        with:
          url: ${{secrets.AIRTABLE_F8CCF_WEBHOOK}}
          method: POST
          body: |
           {
              "Title": "<<<${{on.webhook.outputs.body.Title}}>>>",
              "Target": "${{on.webhook.outputs.body.Target}}",
              "Clockify_ID" : "${{on.webhook.outputs.body.Clockify_ID}}"
            }
