on:
  webhook:

jobs:
  airtable_f8CCf:
    name: get records from airtable
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          body: ${{ toJson(on.webhook.outputs.body) }}
        run: |
          echo body: $body

      - name: 'Get the record from airtable'
        id: step1
        uses: actionsflow/axios@v1
        with:
          url: https://api.airtable.com/v0/appzz4hbwcoJzQaF2/Project%20Database
          method: GET
          content-type: application/json
          params: |
           {
              "api_key": "${{secrets.AIRTABLE_API_TOKEN}}",
              "filterByFormula": "AND(%7BTitle%7D%3D%27Test%27%2CSEARCH(%27Clockify%27%2C%7BTarget%7D)%2C%7BClockify_ID%7D%3D%27%27)",
              "maxRecords": 1
            }

      - naem: Print Response
        run: |
          echo OUTPUT_1: ${{steps.step1.outputs.data}}
          echo OUTPUT_2: ${{fromJSON(steps.step1.outputs.data)}}
