on:
  webhook:

jobs:
  outputs:
    name: outputs
    runs-on: ubuntu-latest
    steps:
      - name: Get outputs
        uses: actions/github-script@v2
        env:
          OUTPUTS_PATH: ${{ on.webhook.outputs.body.Title }}
        with:
          script: |
            const outputs = encodeURIComponent(`${process.env.OUTPUTS_PATH}`)
            return outputs
