on:
  webhook:

jobs:
  airtable_f8CCf:
    name: get records from airtable
    runs-on: ubuntu-latest
    steps:
      - name: Get outputs
        uses: actions/github-script@v2
        id: get-query-encoding
        env:
          OUTPUTS_PATH: ${{ on.webhook.outputs.body.Title }}
        with:
          script: |
            const outputs = encodeURIComponent(`${process.env.OUTPUTS_PATH}`)
            var url = "https://api.airtable.com/v0/appzz4hbwcoJzQaF2/Project%20Database?" + "&filterByFormula=" + "%0A%0A%7BTitle%7D%3D%27" + output + "%27"
            return url

      - name: Get result
        run: echo "${{steps.get-query-encoding.outputs.result}}"
